### ISSUE TITLE
Link to Wiki and Website broken

### ISSUE THREAD

**Issue by srad** [ljchuello/HetznerCloud.Api#4]
The link is broken: https://hetzner.ljchuello.com/

**Comment by ljchuello** [comment]
> The link is broken: https://hetzner.ljchuello.com/

I sincerely apologize. I am switching my domain to another DNS provider.

You can access it using this other link: [ljchuello.gitbook.io/hetznercloud.api](https://ljchuello.gitbook.io/hetznercloud.api/)

If you have any other issues, feel free to reach out again.

**Comment by ljchuello** [comment]
> The link is broken: https://hetzner.ljchuello.com/

You can now access [hetzner.ljchuello.com](https://hetzner.ljchuello.com/)
