### ISSUE TITLE
Updating Firewall not possible

### ISSUE THREAD

**Issue by jason-jxc** [ljchuello/HetznerCloud.Api#5]
```
  HetznerCloudClient hetznerCloudClient = new HetznerCloudClient("KEY");

  Firewall firewall = Task.Run(async () => await hetznerCloudClient.Firewall.Get("ID")).Result;
Firewall.Name = "Firewall - Maintenance ("+DateTime.Now.ToString()+")";
 for (Int32 i = 0; i <= firewall.Rules.Count - 1; i++)
 {
     firewall.Rules[i].SourceIps.Clear();
     firewall.Rules[i].SourceIps.Add("Some IPv4"); // IPv4
     firewall.Rules[i].SourceIps.Add("Some IPv6"); // IPv6
 }

 Firewall fwUpdated = Task.Run(async () => await hetznerCloudClient.Firewall.Update(firewall)).Result;
```
IPv4/6 src: https://myip.is/

Firewall Name is updated, the ip/source is not. Double checked the input / added /32&/128 to ips - still not working...

**Comment by jason-jxc** [comment]
RTFM 😁 

`List<Action> listAction = await hetznerCloudClient.FirewallAction.SetRules(firewall, listRules);`

**Comment by ljchuello** [comment]
> ```
>   HetznerCloudClient hetznerCloudClient = new HetznerCloudClient("KEY");
> 
>   Firewall firewall = Task.Run(async () => await hetznerCloudClient.Firewall.Get("ID")).Result;
> Firewall.Name = "Firewall - Maintenance ("+DateTime.Now.ToString()+")";
>  for (Int32 i = 0; i <= firewall.Rules.Count - 1; i++)
>  {
>      firewall.Rules[i].SourceIps.Clear();
>      firewall.Rules[i].SourceIps.Add("Some IPv4"); // IPv4
>      firewall.Rules[i].SourceIps.Add("Some IPv6"); // IPv6
>  }
> 
>  Firewall fwUpdated = Task.Run(async () => await hetznerCloudClient.Firewall.Update(firewall)).Result;
> ```
> 
> IPv4/6 src: https://myip.is/
> 
> Firewall Name is updated, the ip/source is not. Double checked the input / added /32&/128 to ips - still not working...

Hi. Sorry for the delay.

Do you still need help with this?

**Comment by jason-jxc** [comment]
Hi,

it works as described in the 2nd comment.

Is it intentional that the firewall rules with “hetznerCloudClient.Firewall.Update(firewall)” are not updated?

Thanks for your response ;)

**Comment by ljchuello** [comment]
Great, I don't understand English so I wasn't sure about your comment.

> Is it intentional that the firewall rules with “hetznerCloudClient.Firewall.Update(firewall)” are not updated?

Yes, it's intentional. Personally I didn't like that way either, but it's how the [Hetzner API](https://docs.hetzner.cloud/#firewall-actions-set-rules) is documented.

I'll evaluate doing it the way you indicate, since it would be faster and how to do it.

Anything you need, I'll be happy to help you here.
